spring:
  application:
    name: CorporateDataStorage
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  jpa:
    properties:
      hibernate:
        format_sql: false
        characterEncoding: utf-8
        CharSet: utf-8
        useUnicode: true

server:
  port: 8081

external-system:
  url: ${EXTERNAL_SYSTEM_URL:http://localhost:8084/}

erp-system:
  url: ${ERP_SYSTEM_URL:http://localhost:8080/}

account-system:
  url: ${ACCOUNT_SYSTEM_URL:http://localhost:8083/}

web-app:
  url: ${WEB_APP_URL:http://localhost:8082/}

scheduled:
  timezone: Etc/GMT
  data-migration:
    cron: ${DATA_MIGRATION_CRON:0 0 21 * * ?}