spring:
  application:
    name: AccountingSystem

server:
  port: 8083

external-system:
  url: ${EXTERNAL_SYSTEM_URL:http://localhost:8084/}

erp-system:
  url: ${ERP_SYSTEM_URL:http://localhost:8080/}